spring:
  data:
    mongodb:
      uri: ${DATASOURCE_URL:}
      username: ${DATASOURCE_USERNAME:}
      password: ${DATASOURCE_PASSWORD:''}
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
      max-request-size: ${MAX_REQUEST_SIZE:15MB}
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus